# Generated by Django 5.0.7 on 2024-07-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
