# Generated by Django 5.0.7 on 2024-07-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
