# Generated by Django 5.0.7 on 2024-07-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0002_rename_first_name_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
