# Generated by Django 5.0.7 on 2024-07-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0002_alter_livro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.CharField(max_length=15),
        ),
    ]
