# Generated by Django 5.0.7 on 2024-07-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0003_livro_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
